### ISSUE TITLE
Some conflict and error during generations

### ISSUE THREAD

**Issue by charliebrown777** [Flode-Labs/vid2densepose#8]
![微信图片_20231205232900](https://github.com/Flode-Labs/vid2densepose/assets/36913431/783baff4-a66f-49cf-931b-27a258dfff78)
![微信图片_20231205232938](https://github.com/Flode-Labs/vid2densepose/assets/36913431/46635ac2-1510-4796-bb41-3316e0cb78ca)

I got some conflict error reports when installing the repository, but I can get it to run successfully. Some errors show up in the 2nd image and fail to generate the result. Any solutions to that? Thanks!

**Comment by chen-rn** [comment]
@tadeodonegana Is it possible to run this without CUDA purely on the CPU?

**Comment by tadeodonegana** [comment]
> > I am running into the second error that you're running into. @tadeodonegana Is it possible to run this without CUDA purely on the CPU?
> 
> Hi @chen-rn ,
> 
> After setting the model weights in line 22 add the following line:
> 
> `cfg.MODEL.DEVICE = "cuda" if torch.cuda.is_available() else "cpu"`
> 
> There's a PR that currently proposes this as a solution, you can see it here #11. We are currently waiting to test the change properly and evaluate merging it.
> 
> Please let me know if this works.

This PR was just merged, and it should solve the issue for the app.py file (Gradio version).

**Comment by tadeodonegana** [comment]
CPU support was also added in #16 and the error about Torch not compiled with CUDA enabled should be now solved.
